// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCTspHxWO8qQSaLrLDW1rz1fgSUWHvsP5g',
    appId: '1:191548396096:android:e64c8b9006ffd184be85a5',
    messagingSenderId: '191548396096',
    projectId: 'khatu-shyam-7452d',
    storageBucket: 'khatu-shyam-7452d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEEjsgL3UyJdaZ432dYdbeB0NqbNKvV6U',
    appId: '1:191548396096:ios:ea071860d7b0a3d4be85a5',
    messagingSenderId: '191548396096',
    projectId: 'khatu-shyam-7452d',
    storageBucket: 'khatu-shyam-7452d.firebasestorage.app',
    iosBundleId: 'com.khatushyam.khatushyamApp',
    iosClientId:
        '191548396096-vjesb1fagfk40if91rohtrrjtoe86dg4.apps.googleusercontent.com',
  );
}
